// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqkpyxxzildluqxgbdva.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxa3B5eHh6aWxkbHVxeGdiZHZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0ODY5MzgsImV4cCI6MjA3MzA2MjkzOH0.sJBqv_p1JY8N9mrLnaQTFfWqmAr7mVyk9y415Q_ShC0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});